from datetime import datetime, timedelta, timezone


NOW = datetime.now(timezone.utc)


INCIDENTS = [
    {
        "id": 1,
        "title": "Disparo reportado em via principal",
        "incident_type": "tiroteio",
        "occurred_at": NOW - timedelta(hours=2),
        "source": "central-190",
        "confidence": 0.95,
        "severity_weight": 1.50,
        "status": "confirmado",
        "region": "Centro",
        "lat": -22.9068,
        "lng": -43.1767,
    },
    {
        "id": 2,
        "title": "Roubo de celular em ponto de onibus",
        "incident_type": "roubo",
        "occurred_at": NOW - timedelta(hours=6),
        "source": "boletim-online",
        "confidence": 0.88,
        "severity_weight": 1.20,
        "status": "confirmado",
        "region": "Lapa",
        "lat": -22.9130,
        "lng": -43.1790,
    },
    {
        "id": 3,
        "title": "Tentativa de homicidio em viela",
        "incident_type": "homicidio",
        "occurred_at": NOW - timedelta(hours=10),
        "source": "central-190",
        "confidence": 0.90,
        "severity_weight": 1.60,
        "status": "confirmado",
        "region": "Sao Cristovao",
        "lat": -22.8990,
        "lng": -43.2165,
    },
    {
        "id": 4,
        "title": "Furto em estacionamento comercial",
        "incident_type": "furto",
        "occurred_at": NOW - timedelta(hours=14),
        "source": "boletim-online",
        "confidence": 0.79,
        "severity_weight": 0.90,
        "status": "confirmado",
        "region": "Botafogo",
        "lat": -22.9519,
        "lng": -43.1885,
    },
    {
        "id": 5,
        "title": "Agressao com arma branca",
        "incident_type": "violencia_domestica",
        "occurred_at": NOW - timedelta(hours=18),
        "source": "delegacia-local",
        "confidence": 0.84,
        "severity_weight": 1.10,
        "status": "confirmado",
        "region": "Gloria",
        "lat": -22.9207,
        "lng": -43.1742,
    },
    {
        "id": 6,
        "title": "Roubo em semaforo no horario de pico",
        "incident_type": "roubo",
        "occurred_at": NOW - timedelta(hours=30),
        "source": "central-190",
        "confidence": 0.91,
        "severity_weight": 1.30,
        "status": "confirmado",
        "region": "Flamengo",
        "lat": -22.9360,
        "lng": -43.1760,
    },
    {
        "id": 7,
        "title": "Tiroteio proximo a escola em horario noturno",
        "incident_type": "tiroteio",
        "occurred_at": NOW - timedelta(hours=40),
        "source": "alerta-comunidade",
        "confidence": 0.86,
        "severity_weight": 1.55,
        "status": "confirmado",
        "region": "Complexo do Alemao",
        "lat": -22.8590,
        "lng": -43.2773,
    },
]
